var hamburger = document.querySelector("#hamburger")
var menu = document.querySelector("#menu")
var mode = document.querySelector("#mode")
var screen = document.querySelector("#screen")
var textbox = document.getElementById("textbox")
var text = document.getElementById("text")
var heading = document.getElementById("heading")
var head = document.getElementById("head")
var intro = document.getElementById("intro")
var btn = document.getElementById("btn")
var nav = document.getElementById("nav")
var bmenu = document.getElementById("bmenu")
var PortWind = document.getElementById("PortWind")
var circle = document.getElementById("circle")
var body = document.querySelector("body")
let b = document.querySelector(".body")
var moon = document.querySelector(".moon")
var sun = document.querySelector(".sun")
var pic1 = document.getElementById("pic1")
var pic2 = document.getElementById("pic2")
var  head1 = document.getElementById("head1")
var  head2 = document.getElementById("head2")
var  head3 = document.getElementById("head3")
var fill1 = document.getElementById("fill1")
var fill2 = document.getElementById("fill2")
var fill3 = document.getElementById("fill3")
let image1 = document.querySelector("#image1")
let image2 = document.querySelector("#image2")
let image3 = document.querySelector("#image3")
let image4 = document.querySelector("#image4")
let image5 = document.querySelector("#image5")
let image6 = document.querySelector("#image6")
let image7 = document.querySelector("#image7")
let image8 = document.querySelector("#image8")
let image9 = document.querySelector("#image9")
let image10 = document.querySelector("#image10")
let image11 = document.querySelector("#image11")
let image12 = document.querySelector("#image12")
let card1 = document.getElementById("card1")
let card2 = document.getElementById("card2")
let card3 = document.getElementById("card3")
let card4 = document.getElementById("card4")
let card5 = document.getElementById("card5")
let card6 = document.getElementById("card6")
var hLinks = document.querySelectorAll("hLink")

b.addEventListener("click", ()=>{
    menu.classList.toggle("hidden")
})

hamburger.addEventListener("click", ()=>{
    menu.classList.toggle("hidden")
})

mode.addEventListener("click", ()=>{
    mode.classList.toggle("bg-white")
    body.classList.toggle("bg-slate-800")
    screen.classList.toggle("from-green-600")
    circle.classList.toggle("from-green-900")
    circle.classList.toggle("to-green-400")
    textbox.classList.toggle("bg-slate-800")
    text.classList.toggle("text-blue-200")
    heading.classList.toggle("text-white")
    head.classList.toggle("text-white")
    intro.classList.toggle("text-slate-100")
    btn.classList.toggle("bg-green-700")
    btn.classList.toggle("hover:bg-green-800")
    btn.classList.toggle("hover:bg-green-950")
    nav.classList.toggle("bg-slate-800")
    bmenu.classList.toggle("text-green-600")
    bmenu.classList.toggle("hover:text-green-500")
    PortWind.classList.toggle("text-green-600")
    image1.classList.toggle("hidden")
    image2.classList.toggle("hidden")
    image3.classList.toggle("hidden")
    image4.classList.toggle("hidden")
    image5.classList.toggle("hidden")
    image6.classList.toggle("hidden")
    image7.classList.toggle("hidden")
    image8.classList.toggle("hidden")
    image9.classList.toggle("hidden")
    image10.classList.toggle("hidden")
    image11.classList.toggle("hidden")
    image12.classList.toggle("hidden")
    card1.classList.toggle("bg-slate-600")
    card2.classList.toggle("bg-slate-600")
    card3.classList.toggle("bg-slate-600")
    card4.classList.toggle("bg-slate-600")
    card5.classList.toggle("bg-slate-600")
    card6.classList.toggle("bg-slate-600")
    sun.classList.toggle("hidden")
    moon.classList.toggle("hidden")
    pic1.classList.toggle("hidden")
    pic2.classList.toggle("hidden")
    menu.classList.remove("bg-white")
    menu.classList.toggle("bg-slate-800")
    menu.classList.toggle("text-green-600")
    hamburger.classList.toggle("bg-green-400")
    head1.classList.toggle("text-green-600")
    head2.classList.toggle("text-slate-100")
    head3.classList.toggle("text-slate-100")
    fill3.classList.toggle("bg-green-600")
    fill2.classList.toggle("bg-green-600")
    fill1.classList.toggle("bg-green-600")
})

hLinks.forEach(link => {
    link.addEventListener("click", ()=> {
        menu.classList.toggle("hidden")
    })
})